# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 948249760a1b37d2b6acf0bc81275866ff9990b3e3cd4f8bf88b073c288e1b8125dc5996f9cd8f7f9e4366caadc65ae6176475ed951e481f04c2a84e2b747030

test:
  secret_key_base: b5bc7db55f4a37ee64a24ed3f84a8d6c8dc209e7f5d4d40bad1d404c46950961ff9a6f3770af61684fbbe60a15c8965476de811443cc5fb2401a596bb83ae6f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
